server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${ eureka.client.service-url.defaultZone }

spring:
  application:
    name: purchase-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrapAddress: ${spring.kafka.bootstrapAddress}
    topicName: viewCount

block:
  service:
    api:
      content-type: application/json

member:
  service:
    api:
      content-type: multipart/form-data

logging:
  level:
    root: info
    com.blockpage.purchaseservice.adaptor.infrastructure.message: debug