server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${ eureka.client.service-url.defaultZone }

spring:
  application:
    name: purchase-service

  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${spring.datasource.master.jdbc-url}
      username: ${spring.datasource.master.username}
      password: ${spring.datasource.master.password}

    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${spring.datasource.slave.jdbc-url}
      username: ${spring.datasource.slave.username}
      password: ${spring.datasource.slave.password}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrapAddress: ${spring.kafka.bootstrapAddress}
    topicName: viewCount

block:
  service:
    api:
      content-type: application/json

member:
  service:
    api:
      content-type: application/json

logging:
  level:
    root: info
    com.blockpage.purchaseservice.adaptor.infrastructure.message: debug