name: Deploy

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 기본 체크아웃
      - name: Checkout
        uses: actions/checkout@v3

      # JDK 11 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set Yaml
        uses: microsoft/variable-substitution@v1
        with:
          files: './src/main/resources/application-prod.yml'
        env:
          spring.datasource.master.jdbc-url: ${{ secrets.DB_MASTER_URL }}
          spring.datasource.slave.jdbc-url: ${{ secrets.DB_SLAVE_URL }}
          spring.datasource.master.username: ${{ secrets.DB_USERNAME }}
          spring.datasource.slave.username: ${{ secrets.DB_USERNAME }}
          spring.datasource.master.password: ${{ secrets.DB_PASSWORD }}
          spring.datasource.slave.password: ${{ secrets.DB_PASSWORD }}
          spring.kafka.bootstrapAddress: ${{ secrets.KAFKA_BOOTSTRAP_ADDRESS }}
          eureka.client.service-url.defaultZone: ${{ secrets.EUREKA_DEFAULT_ZONE }}

      # Gradlew 실행 허용
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew
      # Gradle build (Test 제외)
      - name: Build with Gradle
        run: ./gradlew clean build --exclude-task test

      # Docker build
      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker build -t purchase-service .
          docker tag purchase-service geunskoo/purchase-service:${GITHUB_SHA::7}
          docker push geunskoo/purchase-service:${GITHUB_SHA::7}

      # Deploy
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.VM_INSTANCE_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            docker-compose -f docker-compose.purchase.yml down
            docker pull geunskoo/purchase-service:${GITHUB_SHA::7}
            docker tag geunskoo/purchase-service:${GITHUB_SHA::7} purchase-service
            
            docker-compose -f docker-compose.purchase.yml up -d
