name: Deploy

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 기본 체크아웃
    - name: Checkout
      uses: actions/checkout@v3
      
    # Gradlew 실행 허용
    - name: Run chmod to make gradlew executable
      run: chmod +x ./purchase-service/gradlew
      
    # JDK 11 세팅
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Set Yaml
      uses: microsoft/variable-substitution@v1
      with:
        files: ./purchase-service/src/main/resources/application-prod.yml 
      env:
        spring.datasource.url: ${{ secrets.DB_URL }} 
        spring.datasource.username: ${{ secrets.DB_USERNAME }}
        spring.datasource.password: ${{ secrets.DB_PASSWORD }}

    # Gradle build (Test 제외)
    - name: Build with Gradle
      uses: ./purchase-service/gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
